language: java
script:
- gradle build
deploy:
  provider: heroku
  api_key:
    secure: EUW2B8ve7hZ3jsK02l1ao2AnlK0Z6pia5BZffOzxOEqYhbYwO8sLA50Wc19i1SsfN0eg/IJAIjsoTXugQ/S1zKDXwU7zQt7yXi1OD6xnFcQAhK77gcVCMQ4OWoDsn0CxM+/f9LePmZ6nxenkrDswOvjZ82DBpZ4/KZ/ZPIfcdS03bBmK0nqak8PmWUDQp8pUgUolzMBTqivAk9wexcTbAQmgIvyRt6mdjqNKANjRJxi2Yt4ckxr9IjmwCM8NgOsdsvsmH9IYnC+c8KERitYA+Oj0TAVf+QAVFnz8Sknvi854sSEuseJ5as0VzNmX9076ZVdBiGr9DNom6sUMULg8zw/gMNhfTzVjJp9/RGyfHHnKVeq9DnH2dnSuiFOngr2mqMhxy60QvvL2pOaIXHfb2zKsssPdKn54z6trpKnte18c2TzG2ZlRvuWwvKWVA/iQEhXm6z2gH+02Q+U73kTO+gbCK9Jcxm81bLVe8nRgjjNgdLjeJwIg8m7G06sqWYahIQMu5NI7K6nRbTa/KgHkWHdnn44SGlAv2ZEB2mksCG5SoQluVcdjxVriVCejnMBh1dj6pyh4wxwqbFvDX08S+T36LcV0aU33Sqt1Uk5wtut0qIYiL0AyPCf+rp8U8WTFLZTDrB/KIAVEmxSI76rkRtSM8JBo3OjzJpyGZDOeyA8=
